version: '3.3'

services:

    mongodb:
        image: mongo:4.2.20-rc0-bionic
        container_name: mongodb
        hostname: host_mongodb
        ports:
            - ${HOST_PORT}:27017
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=roberto
            - MONGO_INITDB_ROOT_PASSWORD=sanchez
        volumes:
            -  ./DATABASE/datadir:/data/db
            -  ./DATABASE/config/mongod.conf.orig:/etc/mongod.conf.orig
            -  ./DATABASE/config/mongod.conf:/etc/mongod.conf